parser_marketplaces/main/urls.py
from django.urls import path
from main import views

urlpatterns = [
    path('', views.index, name='home'),
    path('about/', views.about, name='about'),
    path('history/', views.history, name='history'),
    path('history/<int:history_id>/', views.history_detail, name='search_history_detail'),
]

parser_marketplaces/parser_marketplaces/urls.py
from django.contrib import admin
from django.urls import path, include
from main.views import page_not_found # Обновленный импорт для 404 страницы

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')), # Включаем URL-маршруты из приложения main для главной страницы
    path('', include('search.urls', namespace='search')), # Включаем URL-маршруты из приложения search с пространством имен
    path('users/', include('users.urls', namespace='users')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = page_not_found
admin.site.site_header = "Панель администрирования"
admin.site.index_title = "Администрирование сайта"

parser_marketplaces/search/urls.py
from django.urls import path
from . import views

app_name = 'search'

urlpatterns = [
    path('search/', views.search_view, name='search_page'),
    path('search/<str:product_name>/', views.search_view, name='product_search'),
]

parser_marketplaces/main/models.py
from django.db import models

parser_marketplaces/main/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse, HttpResponseNotFound
from django.template.loader import render_to_string
import sys
from search.models import SearchQuery, Product, SORT_VALUE_CHOICES
from users.models import User
from wb_api import ProductManager  # ✅
from django.shortcuts import redirect   
from .utils import menu
from django.contrib.auth.decorators import login_required # ✅
import logging
from django.urls import reverse


# Словарь для быстрого получения названия фильтра по его значению
SORT_DICT = dict(SORT_VALUE_CHOICES)
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
    handlers=[logging.StreamHandler()]
)

logger = logging.getLogger(__name__)

def index(request):
    data = {
        'title': 'Главная страница',
        'menu': menu,
    }

    return render(request, 'main/index.html', context=data)

def page_not_found(request, exception):
    return HttpResponseNotFound('Страница не найдена')

def about(request):
    return render(request, 'main/about.html', {'title': 'О сайте', 'menu': menu})

@login_required # ✅
def history(request):
    user_queries = SearchQuery.objects.filter(user=request.user)
    for query in user_queries:
        logger.info(f"{query}")
    data = {
        'title': 'История поиска',
        'requests': user_queries,
        'menu': menu
    }
    return render(request, 'main/history.html', context=data)

def history_detail(request, history_id):
    search_query = get_object_or_404(SearchQuery, id=history_id, user=request.user)
    
    # Получаем товары, связанные с этим запросом
    products = Product.objects.filter(searchquery=search_query)
    
    context = {
        'title': f'Результаты поиска товара "{search_query.query_text}"',
        'products': products,
        'back_url': reverse('history'),
        'back_label': 'Вернуться к Истории поиска',
        'sort_label': SORT_DICT.get(search_query.sort_value, search_query.sort_value),
    }

    return render(request, 'product_results.html', context)

parser_marketplaces/main/templates/main/about.html
{% extends 'base.html' %}

{% block content %}
<h1 class="mb-4">{{ title }}</h1>
<p>Этот сайт демонстрирует возможности поиска товаров на популярных маркетплейсах. Вы можете находить интересующие товары, просматривать их характеристики и сохранять историю своих запросов.</p>
<p>Сервис объединяет результаты с Wildberries, Яндекс.Маркета и Мегамаркета позволяя сортировать их по цене, рейтингу или популярности. Зарегистрированные пользователи получают доступ к истории поиска и могут быстро возвращаться к найденным ранее товарам.</p>
{% endblock %}

parser_marketplaces/main/templates/main/history.html
{% extends 'base.html' %}
{% block content %}
<div class="container my-4">
    <h1 class="mb-4">{{ title }}</h1>
    {% if requests %}
        <ul class="list-group">
        {% for request in requests %}
            <li class="list-group-item d-flex justify-content-between align-items-center">
                <div>
                    <a href="{% url 'search_history_detail' request.id %}" class="fw-bold">
                        {{ request.query_text }}
                    </a>
                    <div class="text-muted small">{{ request.created_at|date:"d.m.Y H:i" }}</div>
                    <div class="text-muted small">Фильтр: {{ request.sort_label }}</div>
                </div>
                <span class="badge bg-secondary">{{ request.id }}</span>
            </li>
        {% endfor %}
        </ul>
    {% else %}
        <p class="text-muted">История поиска пуста</p>
    {% endif %}
</div>
 {% endblock %}

parser_marketplaces/main/templates/main/index.html
{% extends 'base.html' %}

{% block content %}
{% load i18n %}
<div class="p-5 mb-4 bg-white rounded-3"> 
    <div class="container-fluid py-5">
        <h1 class="display-5 fw-bold">{{ title }}</h1>
        <p class="col-md-8 fs-4">
            {% trans "Добро пожаловать на сайт! Здесь вы можете искать товары на различных маркетплейсах и отслеживать историю запросов." %}
        </p>
        <a class="btn btn-primary btn-lg" href="{% url 'search:search_page' %}">{% trans "Перейти к поиску" %}</a>
    </div>
</div>
{% endblock %}